import { FormValues, TransactionForm } from "modules/Transactions";
import type { NextPage } from "next";
import Head from "next/head";

//TODO: PUT data

const New: NextPage = () => {
  const onSubmit = (data: FormValues) => console.log(data);
  return (
    <div>
      <Head>
        <title>New</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <TransactionForm onSubmit={onSubmit} />
    </div>
  );
};

export default New;
